core.autocrlf=input
user.name=Adham084-Phone
user.email=adham.abo.rabie@gmail.com
safe.directory=/storage/emulated/0/Code/Games/Facetor2D
safe.directory=/storage/emulated/0/Code/Games/Facetor2D.git
safe.directory=/storage/emulated/0/Code/Games/CyberTower
safe.directory=/storage/emulated/0/Code/Games/CyberTower.git
safe.directory=/sdcard/Code/Stoneworks/Facetor2D.git
safe.directory=/sdcard/Code/Stoneworks/Facetor2D
safe.directory=/sdcard/Code/Stoneworks/CyberTower
safe.directory=/sdcard/Code/Stoneworks/CyberTower.git
safe.directory=/storage/emulated/0/Code/QliniqRec
safe.directory=/storage/emulated/0/Code/QliniqRec
safe.directory=/sdcard/Code/QliniqRec
credential.https://github.com.helper=
credential.https://github.com.helper=!/data/data/com.termux/files/usr/bin/gh auth git-credential
credential.https://gist.github.com.helper=
credential.https://gist.github.com.helper=!/data/data/com.termux/files/usr/bin/gh auth git-credential
